[package]
name = "structmeta-tests"
version = "0.0.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
structmeta = { path = "../structmeta" }
proc-macro2 = "1.0.52"
syn = { version = "1.0.109", features = ["extra-traits", "full"] }
quote = "1.0.25"
trybuild = "1.0.79"
toml = "0.7.2"
serde = { version = "1.0.155", features = ["derive"] }
anyhow = "1.0.69"
ignore = "0.4.20"
regex = "1.7.1"
