[package]
name = "structmeta-tests"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structmeta = { path = "../structmeta" }

[dev-dependencies]
proc-macro2 = "1.0.24"
syn = "1.0.58"
quote = "1.0.8"
