[package]
name = "structmeta-tests"
version = "0.0.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
structmeta = { path = "../structmeta" }
proc-macro2 = "1.0.24"
syn = { version = "1.0.64", features = ["extra-traits"] }
quote = "1.0.9"

