name: CI

on:
  push:
  pull_request:
  schedule: [cron: "20 5 * * *"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Rustup update stable
        run: rustup update stable
      - name: Show cargo version
        run: cargo --version
      - name: Build
        run: cargo build --verbose
      - name: Build tests
        run: cargo test --verbose --no-run
      - name: Run tests
        run: cargo test --verbose
      - name: Run compile fail tests
        run: cargo test --test compile_fail --verbose -- --ignored
      - name: Clippy
        run: cargo clippy --all-features --tests --lib -- -W clippy::all
        env:
          RUSTFLAGS: -D warnings
      - name: Rustup toolchain install nightly
        run: rustup toolchain install nightly
      - name: Set minimal versions
        run: cargo +nightly update -Z minimal-versions
      - name: Build tests (minimal versions)
        run: cargo +stable test --verbose --no-run
      - name: Run tests (minimal versions)
        run: cargo +stable test --verbose
